ecomprj/core/urls.py
from django.urls import path

from core.partial_views import get_all_categories_by_pagination
from core.views import index, home_page_view, category_list_view, product_list_by_category_view, product_details_view, \
    product_vendor_details_view,product_tags_details_view

app_name = 'core'


class URLS:
    urlpatterns = [
        path('<str:email>/', index, name='index'),
        path('', home_page_view, name='homepage'),
        path('category/categorylist/', category_list_view, name='categorylist'),
        path('category/categorylist/<str:email>/', category_list_view, name='categorylist'),
        path('category/product/', product_list_by_category_view, name='product_list_by_category'),
        path('category/product/<str:email>/', product_list_by_category_view, name='product_list_by_category'),
        path('product/productdetails/', product_details_view, name='product-detail'),
        path('product/productdetails/<str:email>/', product_details_view, name='product-detail'),
        path('product/vendordetails/', product_vendor_details_view, name='vendor-detail'),
        path('product/vendordetails/<str:email>/', product_vendor_details_view, name='vendor-detail'),
        path('product/tags/', product_tags_details_view, name='tags'),
        path('product/tags/<str:email>/', product_tags_details_view, name='tags'),
        path('partial_views/categories/', get_all_categories_by_pagination, name='get_all_categories_by_pagination'),
    ]

    def __dir__(self):
        return URLS.urlpatterns

ecomprj/ecomprj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import core.urls, userauths.urls, utils.urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include((core.urls.URLS, 'core'), namespace='core')),
    path("user/", include((userauths.urls.URLS, 'userauths'), namespace='userauths')),
    path("utils/", include((utils.urls.URLS, 'utils'), namespace='utils')),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/templates/partials/category_dropdown.html
{% for c in categories %}
    {% if forloop.counter <= 10 %}
        <div class="d-flex categori-dropdown-inner">
            {% if forloop.counter <= 5 %}
                <ul>
                    <li>
                        {% if email is None %}
                            <a href="{% url 'core:product_list_by_category' email=None %}?categoryid={{c.id}}"> <img
                                    src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                        {% else %}
                            <a href="{% url 'core:product_list_by_category' email=email %}?categoryid={{c.id}}"> <img
                                    src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                        {% endif %}
                    </li>
                </ul>
            {% else %}
                <ul class="end">
                    <li>
                        {% if email is None %}
                            <a href="{% url 'core:product_list_by_category' email=None %}?categoryid={{c.id}}"> <img
                                    src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                        {% else %}
                            <a href="{% url 'core:product_list_by_category' email=email %}?categoryid={{c.id}}"> <img
                                    src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                        {% endif %}
                    </li>
                </ul>
            {% endif %}
        </div>
    {% else %}
        <div class="more_slide_open" style="display: none">
            <div class="d-flex categori-dropdown-inner">
                {% if forloop.counter <= 15 %}
                    <ul>
                        <li>
                            {% if email is None %}
                                <a href="{% url 'core:product_list_by_category' email=None %}?categoryid={{c.id}}"> <img
                                        src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                            {% else %}
                                <a href="{% url 'core:product_list_by_category' email=email %}?categoryid={{c.id}}"> <img
                                        src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                            {% endif %}
                        </li>
                    </ul>
                {% else %}
                    <ul class="end">
                        <li>
                            {% if email is None %}
                                <a href="{% url 'core:product_list_by_category' email=None %}?categoryid={{c.id}}"> <img
                                        src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                            {% else %}
                                <a href="{% url 'core:product_list_by_category' email=email %}?categoryid={{c.id}}"> <img
                                        src="{{c.image.url}}" alt=""/>{{c.title}}</a>
                            {% endif %}
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endfor %}
<div class="more_categories" id="show_more_toggle_button"><span class="icon"></span> <span class="heading-sm-1">Show more...</span>
</div>

<div class="pagination" id="pagination_links">
    <span class="step-links">
        {% if categories.has_previous %}
            <a href="{% url 'core:get_all_categories_by_pagination' %}?page=1">first</a>
            <a href="{% url 'core:get_all_categories_by_pagination' %}?page={{ categories.previous_page_number }}">previous</a>
        {% endif %}

        {% if categories.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ categories.number }} of {{ categories.paginator.num_pages }}.
            </span>
        {% endif %}

        {% if categories.has_next %}
            <a href="{% url 'core:get_all_categories_by_pagination' %}?page={{ categories.next_page_number }}">next</a>
            <a href="{% url 'core:get_all_categories_by_pagination' %}?page={{ categories.paginator.num_pages }}">last</a>
        {% endif %}
    </span>
</div>
<script>
    document.getElementById('show_more_toggle_button').addEventListener('click', function () {
        toggleShowButton();
    });

</script>